server_address : "127.0.0.1"
server_port : 4567
buffersize : 1024
max_connection : 12

mysql_username : "root"
mysql_host : "127.0.0.1"
mysql_pwd : "root"
mysql_database : "nosql"
mysql_port : 3306

mongodb_address : "mongodb://localhost:27017/"
mongodb_database : "test"

ftp_ip: 'localhost'
ftp_port: 21
ftp_username: "Jerry"
ftp_password: "123"