# -*- coding: utf-8 -*-

# Form implementation generated from reading ui-submit file 'login.ui-submit'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#import source.prc


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(600, 450))
        Form.setMaximumSize(QtCore.QSize(600, 450))
        self.user = QtWidgets.QLabel(Form)
        self.user.setGeometry(QtCore.QRect(150, 170, 61, 31))
        self.user.setStyleSheet("font: 12pt \"Agency FB\";")
        self.user.setObjectName("user")
        self.pwd = QtWidgets.QLabel(Form)
        self.pwd.setGeometry(QtCore.QRect(160, 230, 51, 31))
        self.pwd.setStyleSheet("font: 12pt \"Agency FB\";")
        self.pwd.setObjectName("pwd")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(220, 160, 221, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 230, 221, 41))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(260, 290, 91, 21))
        self.checkBox.setObjectName("checkBox")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(370, 290, 72, 15))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(160, 330, 291, 41))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    font: 12pt \"Agency FB\";\n"
"border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.txButton = QtWidgets.QPushButton(Form)
        self.txButton.setGeometry(QtCore.QRect(250, 40, 100, 100))
        self.txButton.setMinimumSize(QtCore.QSize(100, 100))
        self.txButton.setMaximumSize(QtCore.QSize(100, 100))
        self.txButton.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"border-image:url(:/login/images/tx.png);\n"
"}")
        self.txButton.setText("")
        self.txButton.setObjectName("txButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 410, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(462, 410, 111, 28))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.user.setText(_translate("Form", "用户名"))
        self.pwd.setText(_translate("Form", "密码"))
        self.checkBox.setText(_translate("Form", "记住密码"))
        self.label.setText(_translate("Form", "忘记密码？"))
        self.pushButton.setText(_translate("Form", "登录"))
        self.pushButton_2.setText(_translate("Form", "注册账号"))
        self.pushButton_3.setText(_translate("Form", "短信验证码登录"))

if __name__ == "__main__":
	import sys
	QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)

	app =  QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_Form()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())
