# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yz1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QQ(object):
    def setupUi(self, QQ):
        QQ.setObjectName("QQ")
        QQ.resize(771, 522)
        self.textBrowser = QtWidgets.QTextBrowser(QQ)
        self.textBrowser.setGeometry(QtCore.QRect(0, 50, 601, 411))
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit = QtWidgets.QLineEdit(QQ)
        self.lineEdit.setGeometry(QtCore.QRect(0, 460, 601, 61))
        self.lineEdit.setStyleSheet("coloe:rgb(0, 0, 0);\n"
"font: 9pt \"Axure Handwriting\";\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(QQ)
        self.pushButton.setGeometry(QtCore.QRect(600, 460, 171, 61))
        self.pushButton.setStyleSheet("color: black(255, 0, 0);\n"
"font: 25 24pt \"Bahnschrift\";")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser_2 = QtWidgets.QTextBrowser(QQ)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 0, 781, 51))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(QQ)
        self.textBrowser_3.setGeometry(QtCore.QRect(600, 50, 171, 411))
        self.textBrowser_3.setObjectName("textBrowser_3")

        self.retranslateUi(QQ)
        QtCore.QMetaObject.connectSlotsByName(QQ)

    def retranslateUi(self, QQ):
        _translate = QtCore.QCoreApplication.translate
        QQ.setWindowTitle(_translate("QQ", "Dialog"))
        self.textBrowser.setHtml(_translate("QQ", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">输出内容</p></body></html>"))
        self.lineEdit.setText(_translate("QQ", "asdsd 输入内容"))
        self.pushButton.setText(_translate("QQ", "发送"))
        self.textBrowser_2.setHtml(_translate("QQ", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">用户名</p></body></html>"))
        self.textBrowser_3.setHtml(_translate("QQ", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">图片</p></body></html>"))

if __name__ == "__main__":
	import sys
	QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)

	app =  QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_QQ()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())
